### ISSUE TITLE
[Issue] Command doesn't work.

### ISSUE THREAD

**Issue by dunaland1** [slipcor/PVPStats#21]
Hello,

The command for seing someone else's pvpstats isn't working for me. When I type /pvpstats name it brings out the help menu (pvpstats help). No errors in console and nothing in debug (Just 19.09.30 15:24:44 [INFO] [PS-debug] [p:KamosRZ]890 onCommand!).

I am using the latest version on spigot (not the one here on github) - 1.3.7 and my server is running latest paper 1.14.4 - 207

**Comment by slipcor** [comment]
While doing the rewrite I noticed that the handling of "/pvpstats [playername]" is very risky because it could possibly never lead to anyone getting help about using the plugin unless they KNOW that "/pvpstats help" is a thing.

I will add the fallback to allowing to use the plugin like this if the player exists. If they do not, you do get the message prompting you to use the new logic /pvpstats show [playername] because that way we all know what you tried to do :)

**Comment by slipcor** [comment]
I uploaded the build here, as currently spigot seems to not let me log in :(

http://pa.slipcor.net/pvpstats.jar
